package com.ep360.data.models;
// Generated Mar 6, 2015 9:55:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VoyHeader generated by hbm2java
 */
@Entity
@Table(name="voy_header"
    ,catalog="voyage"
)
public class VoyHeader  implements java.io.Serializable {


     private VoyHeaderId id;
     private String voyType;
     private int voyEstNo;
     private int vesselNo;
     private String tcOper;
     private String trader;
     private String voyOper;
     private String tradeId;
     private String voyStatus;
     private boolean zeroProfInd;
     private float totDemdes;
     private float totAdcomm;
     private float totBrok;
     private float totFrttax;
     private float totLinterm;
     private float totPortChrg;
     private float totBunkChrg;
     private float cev;
     private float ilohc;
     private float ballBonus;
     private float routServ;
     private int addcostitemNo;
     private float addcost;
     private float dailyHireCost;
     private float dailyHireAddcomm;
     private float totRev;
     private float operExp;
     private float totHire;
     private float totExpense;
     private float totProfit;
     private Date createdOn;
     private String createdBy;
     private Date lastCreatedOn;
     private String lastCreatedBy;

    public VoyHeader() {
    }

    public VoyHeader(VoyHeaderId id, String voyType, int voyEstNo, int vesselNo, String tcOper, String trader, String voyOper, String tradeId, String voyStatus, boolean zeroProfInd, float totDemdes, float totAdcomm, float totBrok, float totFrttax, float totLinterm, float totPortChrg, float totBunkChrg, float cev, float ilohc, float ballBonus, float routServ, int addcostitemNo, float addcost, float dailyHireCost, float dailyHireAddcomm, float totRev, float operExp, float totHire, float totExpense, float totProfit, Date createdOn, String createdBy, Date lastCreatedOn, String lastCreatedBy) {
       this.id = id;
       this.voyType = voyType;
       this.voyEstNo = voyEstNo;
       this.vesselNo = vesselNo;
       this.tcOper = tcOper;
       this.trader = trader;
       this.voyOper = voyOper;
       this.tradeId = tradeId;
       this.voyStatus = voyStatus;
       this.zeroProfInd = zeroProfInd;
       this.totDemdes = totDemdes;
       this.totAdcomm = totAdcomm;
       this.totBrok = totBrok;
       this.totFrttax = totFrttax;
       this.totLinterm = totLinterm;
       this.totPortChrg = totPortChrg;
       this.totBunkChrg = totBunkChrg;
       this.cev = cev;
       this.ilohc = ilohc;
       this.ballBonus = ballBonus;
       this.routServ = routServ;
       this.addcostitemNo = addcostitemNo;
       this.addcost = addcost;
       this.dailyHireCost = dailyHireCost;
       this.dailyHireAddcomm = dailyHireAddcomm;
       this.totRev = totRev;
       this.operExp = operExp;
       this.totHire = totHire;
       this.totExpense = totExpense;
       this.totProfit = totProfit;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.lastCreatedOn = lastCreatedOn;
       this.lastCreatedBy = lastCreatedBy;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="tenantId", column=@Column(name="TenantId", nullable=false, length=36) ), 
        @AttributeOverride(name="clientId", column=@Column(name="ClientId", nullable=false, length=10) ), 
        @AttributeOverride(name="voyNo", column=@Column(name="Voy_no", nullable=false, length=10) ) } )
    public VoyHeaderId getId() {
        return this.id;
    }
    
    public void setId(VoyHeaderId id) {
        this.id = id;
    }

    
    @Column(name="Voy_type", nullable=false, length=4)
    public String getVoyType() {
        return this.voyType;
    }
    
    public void setVoyType(String voyType) {
        this.voyType = voyType;
    }

    
    @Column(name="Voy_est_no", nullable=false)
    public int getVoyEstNo() {
        return this.voyEstNo;
    }
    
    public void setVoyEstNo(int voyEstNo) {
        this.voyEstNo = voyEstNo;
    }

    
    @Column(name="vessel_no", nullable=false)
    public int getVesselNo() {
        return this.vesselNo;
    }
    
    public void setVesselNo(int vesselNo) {
        this.vesselNo = vesselNo;
    }

    
    @Column(name="tc_oper", nullable=false, length=12)
    public String getTcOper() {
        return this.tcOper;
    }
    
    public void setTcOper(String tcOper) {
        this.tcOper = tcOper;
    }

    
    @Column(name="trader", nullable=false, length=12)
    public String getTrader() {
        return this.trader;
    }
    
    public void setTrader(String trader) {
        this.trader = trader;
    }

    
    @Column(name="voy_oper", nullable=false, length=12)
    public String getVoyOper() {
        return this.voyOper;
    }
    
    public void setVoyOper(String voyOper) {
        this.voyOper = voyOper;
    }

    
    @Column(name="trade_id", nullable=false, length=6)
    public String getTradeId() {
        return this.tradeId;
    }
    
    public void setTradeId(String tradeId) {
        this.tradeId = tradeId;
    }

    
    @Column(name="voy_status", nullable=false, length=10)
    public String getVoyStatus() {
        return this.voyStatus;
    }
    
    public void setVoyStatus(String voyStatus) {
        this.voyStatus = voyStatus;
    }

    
    @Column(name="zero_prof_ind", nullable=false)
    public boolean isZeroProfInd() {
        return this.zeroProfInd;
    }
    
    public void setZeroProfInd(boolean zeroProfInd) {
        this.zeroProfInd = zeroProfInd;
    }

    
    @Column(name="tot_demdes", nullable=false, precision=12, scale=0)
    public float getTotDemdes() {
        return this.totDemdes;
    }
    
    public void setTotDemdes(float totDemdes) {
        this.totDemdes = totDemdes;
    }

    
    @Column(name="tot_adcomm", nullable=false, precision=12, scale=0)
    public float getTotAdcomm() {
        return this.totAdcomm;
    }
    
    public void setTotAdcomm(float totAdcomm) {
        this.totAdcomm = totAdcomm;
    }

    
    @Column(name="tot_brok", nullable=false, precision=12, scale=0)
    public float getTotBrok() {
        return this.totBrok;
    }
    
    public void setTotBrok(float totBrok) {
        this.totBrok = totBrok;
    }

    
    @Column(name="tot_frttax", nullable=false, precision=12, scale=0)
    public float getTotFrttax() {
        return this.totFrttax;
    }
    
    public void setTotFrttax(float totFrttax) {
        this.totFrttax = totFrttax;
    }

    
    @Column(name="tot_linterm", nullable=false, precision=12, scale=0)
    public float getTotLinterm() {
        return this.totLinterm;
    }
    
    public void setTotLinterm(float totLinterm) {
        this.totLinterm = totLinterm;
    }

    
    @Column(name="tot_port_chrg", nullable=false, precision=12, scale=0)
    public float getTotPortChrg() {
        return this.totPortChrg;
    }
    
    public void setTotPortChrg(float totPortChrg) {
        this.totPortChrg = totPortChrg;
    }

    
    @Column(name="tot_bunk_chrg", nullable=false, precision=12, scale=0)
    public float getTotBunkChrg() {
        return this.totBunkChrg;
    }
    
    public void setTotBunkChrg(float totBunkChrg) {
        this.totBunkChrg = totBunkChrg;
    }

    
    @Column(name="cev", nullable=false, precision=12, scale=0)
    public float getCev() {
        return this.cev;
    }
    
    public void setCev(float cev) {
        this.cev = cev;
    }

    
    @Column(name="ilohc", nullable=false, precision=12, scale=0)
    public float getIlohc() {
        return this.ilohc;
    }
    
    public void setIlohc(float ilohc) {
        this.ilohc = ilohc;
    }

    
    @Column(name="ball_bonus", nullable=false, precision=12, scale=0)
    public float getBallBonus() {
        return this.ballBonus;
    }
    
    public void setBallBonus(float ballBonus) {
        this.ballBonus = ballBonus;
    }

    
    @Column(name="rout_serv", nullable=false, precision=12, scale=0)
    public float getRoutServ() {
        return this.routServ;
    }
    
    public void setRoutServ(float routServ) {
        this.routServ = routServ;
    }

    
    @Column(name="addcostitem_no", nullable=false)
    public int getAddcostitemNo() {
        return this.addcostitemNo;
    }
    
    public void setAddcostitemNo(int addcostitemNo) {
        this.addcostitemNo = addcostitemNo;
    }

    
    @Column(name="addcost", nullable=false, precision=12, scale=0)
    public float getAddcost() {
        return this.addcost;
    }
    
    public void setAddcost(float addcost) {
        this.addcost = addcost;
    }

    
    @Column(name="daily_hire_cost", nullable=false, precision=12, scale=0)
    public float getDailyHireCost() {
        return this.dailyHireCost;
    }
    
    public void setDailyHireCost(float dailyHireCost) {
        this.dailyHireCost = dailyHireCost;
    }

    
    @Column(name="daily_hire_addcomm", nullable=false, precision=12, scale=0)
    public float getDailyHireAddcomm() {
        return this.dailyHireAddcomm;
    }
    
    public void setDailyHireAddcomm(float dailyHireAddcomm) {
        this.dailyHireAddcomm = dailyHireAddcomm;
    }

    
    @Column(name="tot_rev", nullable=false, precision=12, scale=0)
    public float getTotRev() {
        return this.totRev;
    }
    
    public void setTotRev(float totRev) {
        this.totRev = totRev;
    }

    
    @Column(name="oper_exp", nullable=false, precision=12, scale=0)
    public float getOperExp() {
        return this.operExp;
    }
    
    public void setOperExp(float operExp) {
        this.operExp = operExp;
    }

    
    @Column(name="tot_hire", nullable=false, precision=12, scale=0)
    public float getTotHire() {
        return this.totHire;
    }
    
    public void setTotHire(float totHire) {
        this.totHire = totHire;
    }

    
    @Column(name="tot_expense", nullable=false, precision=12, scale=0)
    public float getTotExpense() {
        return this.totExpense;
    }
    
    public void setTotExpense(float totExpense) {
        this.totExpense = totExpense;
    }

    
    @Column(name="tot_profit", nullable=false, precision=12, scale=0)
    public float getTotProfit() {
        return this.totProfit;
    }
    
    public void setTotProfit(float totProfit) {
        this.totProfit = totProfit;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", nullable=false, length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", nullable=false, length=12)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_created_on", nullable=false, length=19)
    public Date getLastCreatedOn() {
        return this.lastCreatedOn;
    }
    
    public void setLastCreatedOn(Date lastCreatedOn) {
        this.lastCreatedOn = lastCreatedOn;
    }

    
    @Column(name="last_created_by", nullable=false, length=12)
    public String getLastCreatedBy() {
        return this.lastCreatedBy;
    }
    
    public void setLastCreatedBy(String lastCreatedBy) {
        this.lastCreatedBy = lastCreatedBy;
    }




}


