package com.ep360.data.models;
// Generated Mar 6, 2015 9:55:17 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VoyHeaderId generated by hbm2java
 */
@Embeddable
public class VoyHeaderId  implements java.io.Serializable {


     private String tenantId;
     private String clientId;
     private String voyNo;

    public VoyHeaderId() {
    }

    public VoyHeaderId(String tenantId, String clientId, String voyNo) {
       this.tenantId = tenantId;
       this.clientId = clientId;
       this.voyNo = voyNo;
    }
   


    @Column(name="TenantId", nullable=false, length=36)
    public String getTenantId() {
        return this.tenantId;
    }
    
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }


    @Column(name="ClientId", nullable=false, length=10)
    public String getClientId() {
        return this.clientId;
    }
    
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }


    @Column(name="Voy_no", nullable=false, length=10)
    public String getVoyNo() {
        return this.voyNo;
    }
    
    public void setVoyNo(String voyNo) {
        this.voyNo = voyNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VoyHeaderId) ) return false;
		 VoyHeaderId castOther = ( VoyHeaderId ) other; 
         
		 return ( (this.getTenantId()==castOther.getTenantId()) || ( this.getTenantId()!=null && castOther.getTenantId()!=null && this.getTenantId().equals(castOther.getTenantId()) ) )
 && ( (this.getClientId()==castOther.getClientId()) || ( this.getClientId()!=null && castOther.getClientId()!=null && this.getClientId().equals(castOther.getClientId()) ) )
 && ( (this.getVoyNo()==castOther.getVoyNo()) || ( this.getVoyNo()!=null && castOther.getVoyNo()!=null && this.getVoyNo().equals(castOther.getVoyNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTenantId() == null ? 0 : this.getTenantId().hashCode() );
         result = 37 * result + ( getClientId() == null ? 0 : this.getClientId().hashCode() );
         result = 37 * result + ( getVoyNo() == null ? 0 : this.getVoyNo().hashCode() );
         return result;
   }   


}


